baseURL = "https://katana.iwr.uni-heidelberg.de" 
languageCode = "en-us"
title = "Home"

[menu]
# lower weight will come first
  [[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"
    weight = -5

  [[menu.main]]
    identifier = "news"
    name = "News & Events" 
    url = "/news/"
    weight = -4 

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = -3

  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = -2

  [[menu.main]]
    identifier = "teaching"
    name = "Teaching"
    url = "/teaching/"
    weight = -1 
 
[params]
  pageTitle = "Numerical Analysis and UQ"

[markup]
  defaultMarkdownHandler = "blackfriday"

